---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/philipsd6/pre-commit-hook-git-crypt
    rev: v1.0.1
    hooks:
      - id: check-git-crypt-status
  - repo: https://github.com/dfm/black_nbconvert
    rev: v0.3.0
    hooks:
      - id: black_nbconvert
